resources:
  - frontend/deploy.yml
images:
  - name: 132672257147.dkr.ecr.us-east-1.amazonaws.com/devopsnanuvem/dev/front
    newTag: v5.0
    newName: 132672257147.dkr.ecr.us-east-1.amazonaws.com/devopsnanuvem/dev/front
---
resources:
  - webcolor/rollout-blue-green.yml
images:
  - name: fabricioveronez/web-color
    newTag: blue
    newName: fabricioveronez/web-color